site:
  title: "Filipe Soares - Timeline"
  description: "Welcome to my personal timeline"
personal:
  name: "Filipe Soares"
  avatar: "https://github.com/filipecsoares.png"
  socialNetworks:
    youtube: "https://www.youtube.com/channel/UC_NjE4TAOhnqmshjfVoCL0Q"
    github: "https://www.github.com/filipecsoares"